import os

# dataset
TEXT_FILE_PATH = "three_body.txt"
WINDOWS_SIZE = 100
SHIFT = 1
BATCH_SIZE = 64
SHUFFLE_BUFFER_SIZE = 1000

# model
EMBEDDING_DIM = 256
RNN_UNITES = 1024

# save
CHECKPOINT_SHIFT = TEXT_FILE_PATH[:-4]
CHECKPOINT_ROOT = os.path.join(".log", CHECKPOINT_SHIFT)
CHECKPOINT_PATH = os.path.join(CHECKPOINT_ROOT, CHECKPOINT_SHIFT, "checkpoint_{epoch}")

# train
EPOCHS = 30

# generate
NUM_GENERATE = 3000
START_STRING = u"蒙娜丽莎"
